spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MVCC=TURE
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: ture

logging:
  level:
    org.hibernate.SQL: debug
